// <auto-generated />
using DLSmartAppraisal.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DLSmartAppraisal.Migrations.Designation
{
    [DbContext(typeof(DesignationContext))]
    [Migration("20251005160222_uer1")]
    partial class uer1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DLSmartAppraisal.Model.DesignationDetails", b =>
                {
                    b.Property<int>("DesgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesgId"));

                    b.Property<string>("DesgName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DesgId");

                    b.ToTable("designations");
                });
#pragma warning restore 612, 618
        }
    }
}
